#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/starship.toml ~/.config/startship.toml
ln -sf ~/dotfiles/sway ~/.config/sway
ln -sf ~/dotfiles/waybar ~/.config/waybar

echo "Dotfiles linked!"
